apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: static-pages

resources:
  - ../../../bases/static-pages

generators:
  - ./secret-generator.yaml

images:
  - name: ghcr.io/spechtlabs/staticpages
    newTag: v0.1.5
